// <auto-generated />
using System;
using DndSessionManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndSessionManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821220331_AddCharacterChildTables")]
    partial class AddCharacterChildTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndSessionManager.Api.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveLevelSheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalFeatures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlliesOrganizations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeathSaveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DeathSaveSuccesses")
                        .HasColumnType("integer");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Eyes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeaturesTraits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HitDiceTotal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HpCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("HpTemporary")
                        .HasColumnType("integer");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<bool>("Inspiration")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OtherProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassivePerception")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("Wealth")
                        .HasColumnType("bigint");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveLevelSheetId");

                    b.HasIndex("GameId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AtkBonus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAttacks");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterLevelSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<int>("HpMax")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterLevelSheets");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Proficient")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSaves");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Proficient")
                        .HasColumnType("boolean");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSpell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("LevelSheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Prepared")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LevelSheetId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSpellSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Expended")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("LevelSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelSheetId");

                    b.ToTable("CharacterSpellSlots");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSpellcasting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LevelSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpellAttackBonus")
                        .HasColumnType("integer");

                    b.Property<int>("SpellSaveDc")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelSheetId")
                        .IsUnique();

                    b.ToTable("CharacterSpellcastings");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.Character", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.CharacterLevelSheet", "ActiveLevelSheet")
                        .WithMany()
                        .HasForeignKey("ActiveLevelSheetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DndSessionManager.Api.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveLevelSheet");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterAttack", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.Character", "Character")
                        .WithMany("Attacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterItem", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterLevelSheet", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.Character", "Character")
                        .WithMany("LevelSheets")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSave", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.Character", "Character")
                        .WithMany("Saves")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSkill", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSpell", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.CharacterLevelSheet", "LevelSheet")
                        .WithMany("Spells")
                        .HasForeignKey("LevelSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelSheet");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSpellSlot", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.CharacterLevelSheet", "LevelSheet")
                        .WithMany("SpellSlots")
                        .HasForeignKey("LevelSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelSheet");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterSpellcasting", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.CharacterLevelSheet", "LevelSheet")
                        .WithOne("Spellcasting")
                        .HasForeignKey("DndSessionManager.Api.Entities.CharacterSpellcasting", "LevelSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelSheet");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.Quote", b =>
                {
                    b.HasOne("DndSessionManager.Api.Entities.Game", "Game")
                        .WithMany("Quotes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.Character", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Items");

                    b.Navigation("LevelSheets");

                    b.Navigation("Saves");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.CharacterLevelSheet", b =>
                {
                    b.Navigation("SpellSlots");

                    b.Navigation("Spellcasting");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("DndSessionManager.Api.Entities.Game", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
